# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    telegram.bot_token: '%env(BOT_TOKEN)%'
    telegram.bot_username: '%env(BOT_USERNAME)%'
    telegram.commands_path: '%kernel.project_dir%/src/Telegram/Command'
    rate_limit.max_files: '%env(int:RATE_LIMIT_FILES)%'
    rate_limit.window_seconds: '%env(int:RATE_LIMIT_WINDOW)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $botToken: '%telegram.bot_token%'
            $botUsername: '%telegram.bot_username%'
            $rateLimitMaxFiles: '%rate_limit.max_files%'
            $rateLimitWindowSeconds: '%rate_limit.window_seconds%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Telegram/Command/'  # Исключаем команды бота (они не являются Symfony сервисами)

    # Telegram Bot Service
    App\Service\Telegram\BotService:
        arguments:
            $commandsPath: '%telegram.commands_path%'

    # ChatExportProcessor - публичный для доступа из GenericmessageCommand
    App\Service\ChatExportProcessor:
        public: true

    # Parser Factory с автоматической инъекцией всех парсеров
    App\Service\Parser\ParserFactory:
        arguments:
            $parsers: !tagged_iterator app.parser

    # Теги для парсеров
    App\Service\Parser\JsonExportParser:
        tags: ['app.parser']

    App\Service\Parser\HtmlExportParser:
        tags: ['app.parser']